
version: "3"
services:
  oceanportal:
    build:
      context: .
    hostname: oceanportal
    ports:
      - "0.0.0.0:80:80"
    # Uncomment and adapt this if you are using a jwilder/nginx-proxy
    #environment:
    #  - VIRTUAL_HOST=sub.domain.com
    volumes:
    - ./data:/opt/data
    # - .:/ocean-portal # Uncomment this for development (so that changes to source are picked up live)
    #restart: on-failure:5
    user: root
    #command: mkdir -p /opt/ocean-portal && python setup.py install --root=/opt/ocean-portal/
    
    
